### PR TITLE
Dm 2179

### PR DESCRIPTION
**Pull request by JoshingYou1**
### JIRA issue link
https://agile6.atlassian.net/browse/DM-2179

## Description - what does this code do?
1. Adds the `Relevant to you` page.
2. Adjusts breadcrumb styling to match new figma designs.

## Testing done - how did you test it/steps on how can another person can test it 
Run `bundle:install`

1. Without logging in, try to browse to `/relevant-to-you`.
2. Make sure you are redirected to the homepage.
3. Now, log in as an admin and browse to `/relevant-to-you`.
4. If you already have `Bookmarked` practices, you should see the `Your bookmarked practices` section at the top.
5. Bookmark a few practices.
6. On the `Relevant to you` page, make sure they are ordered by when you bookmarked them.
7. In your rails console, check if any of your `UserPractices` that were already existing before this exercise have a `nil` value for `time_favorited`. If they do, make sure they are placed after the ones that have a correct value for `time_favorited`.
8. Un-bookmark all of your bookmarked practices.
9. Refresh the page and make sure the `Your bookmarked practices` section is no longer on the page.
10. Visit the PE `Introduction` page of a practice of your choice.
11. Scroll down to the `Practice origin` section and choose the `Facility` option and select a facility of your choosing.
12. Go to your rails console and check if any other practices share this same facility. If not, edit two more practices so they have the same facility as the on you chose above.
13. Visit `/edit-profile` and in the `location` field, add the same facility name as the three practices you edited above.
14. Go to `/relevant-to-you`.
15. Make sure you see the same three practices from above under the `Based on your location` section.
16. Make sure you don't see a `See more practices` link below the three cards`.
17. Add one more practice that shares the same facility as the three others from above to increase the count to four.
18. Go to `/relevant-to-you`.
19. Make sure you now see the `See more practices` link.
20. Click the link, and make sure it takes you to the search page with a query of the four `Based on your location` practices' facility name.
21. Go to `/edit-profile` and remove the facility from your `Location` field, so that it is blank.
22. Go to `/relevant-to-you` and under the `Based on your location` section, make sure you see some text stating you don't have a location and a link that goes to `yourit.va.gov`.
23. Go to `/` and bookmark four or more practices.
24. Go to `/relevant-to-you` and make sure you see a `Load more` button.
25. Click on the button and make sure the next set of practices load correctly.
26. Make sure the breadcrumb styling matches the Figma designs.
27. Make sure everything looks good on mobile.
**Important: The `Relevant to you` Title, while on a `320px` viewport, can stretch to two lines(per UX).**

## Screenshots, Gifs, Videos from application (if applicable)
Screen Shot 2020-11-15 at 4 37 47 PM
Screen Shot 2020-11-15 at 4 37 19 PM
Screen Shot 2020-11-15 at 4 39 28 PM

## Link to mock-ups/mock ups (image file if you have it) (if applicable)
https://www.figma.com/file/y9U9oLXTGe24O9W3X5UoYW/Home-%2B-Search-V2?node-id=1%3A171

## Acceptance criteria
- Build Based on Location
- Build favorites
- If no favorites, show no favorites
- DON’T BUILD BASED ON YOUR ROLE AND SAVED SEARCH
- See More takes them to a search result for that thing (ie location)

## Definition of done
- [X] Unit tests written (if applicable)
- [X] e2e/accessibility tests written (if applicable)
- [X] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [X] A link has been provided to the originating JIRA issue
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by emyl3 — CHANGES_REQUESTED** [review]
Great work, Josh! The pagination is very slick!

There was one bug I noticed. To repro:
- Log in as a user with 4 practices bookmarked
- Go to `/relevant-to-you`
- Unbookmark all 3 practices that are currently shown
- Then hit "Load more" and see a 500 error because the practices are being unbookmarked so there technically isn't a "next page" of practices that are bookmarked

**Comment by JoshingYou1** [comment]
> Great work, Josh! The pagination is very slick!
> 
> There was one bug I noticed. To repro:
> 
> * Log in as a user with 4 practices bookmarked
> * Go to `/relevant-to-you`
> * Unbookmark all 3 practices that are currently shown
> * Then hit "Load more" and see a 500 error because the practices are being unbookmarked so there technically isn't a "next page" of practices that are bookmarked

The team decided to go with a page refresh for now, in order to resolve this issue. Code has been updated! Thank you for catching this!

**Review by emyl3 — APPROVED** [review]
Looks good to me! 👍 Great work, Josh!

**Review by bradjohnson92008 — APPROVED** [review]
Great work Josh!  Looks really good.  The only thing in noticed in all the scenarios was that when I hit the Load More button... there is no indication to the user that the page is busy...  I thought that when the location.refresh() was called the reload button would spin.. but I could see in the terminal the app was working fine.. so not a show stopper for me.

**Pull request merged**
