### PR TITLE
Dm 2107

### PR DESCRIPTION
**Pull request by emyl3**
### JIRA issue link
[DM-2107](https://agile6.atlassian.net/browse/DM-2107)

## Description - what does this code do?
This PR addresses the following:
- Removes the image editor from the edit profile page
- Ensures duplicate "Add another" fields from not appearing in the introduction practice editor page when clicking on the "Introduction" link in the side navigation
- Updates the image editor on the Introduction page with the file component

## Testing done - how did you test it/steps on how can another person can test it 
**Profile Page**
1. Log in as a user
2. Go to the user's profile page
3. Click the "Edit Profile" icon
4. Ensure you are no longer able to edit the user's profile picture

**Introduction PE - Add Another fields**
1. Log in as a user that can edit a practice
2. Navigate to a practice's practice editor
3. Navigate to the Introduction editor page
4. Click on the "Introduction" link in the practice editor side navigation
5. Ensure multiple "Add another" fields do not appear
6. Ensure you can still add more fields and save the practice
7. Ensure that the added fields are displayed in the editor and view

**Introduction PE - updated image editor**
1. Log in as a user that can edit a practice
2. Navigate to a practice's practice editor
3. Navigate to the Introduction editor page
4. Ensure you can upload, crop, and remove and image and save the practice
5. Ensure you do not see an upload field when loading the editor for a practice with a thumbnail until you click "remove image"
6. Ensure you get error messages when the image you upload does not meet requirements (i.e. too small or too large of a file size)
7. Ensure you can only upload images
8. Ensure when you crop an image a new cropped image appears

## Screenshots, Gifs, Videos from application (if applicable)
Screen Shot 2020-09-30 at 12 14 53 PM

Screen Shot 2020-09-30 at 12 16 34 PM

Screen Shot 2020-09-30 at 12 16 45 PM

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Unit tests written (if applicable)
- [X] e2e/accessibility tests written (if applicable)
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [X] A link has been provided to the originating JIRA issue
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by bradjohnson92008 — COMMENTED** [review]
Functionality looks good Elisa - Great job.  Only thing I noticed was that there was a lot of white space in the Edit-Profile page between the text and the actual profile image.

image

**Review by JoshingYou1 — CHANGES_REQUESTED** [review]
Great work Elisa!! Just one thing I noticed, which might be the same issue Brad had. If the user currently has a profile image, some hidden elements are taking up space. I think the issues are on lines `56` and `60-62` in `edit_profile_html.erb`. Replacing the `hidden` class with `display-none` worked for me. 
Screen Shot 2020-10-01 at 1 35 06 PM

**Comment by emyl3** [comment]
@JoshingYou1 @bradjohnson92008 I addressed your comments! :) Let me know if you see any other issues! Thank you!

**Review by JoshingYou1 — APPROVED** [review]
Looks good to me. Great job Elisa!!

**Review by bradjohnson92008 — APPROVED** [review]
Great job Elisa, looks good!

**Pull request merged**
