### PR TITLE
Dm 2185

### PR DESCRIPTION
**Pull request by JoshingYou1**
### JIRA issue link
https://agile6.atlassian.net/browse/DM-2185

## Description - what does this code do?
1. Brings new features to the search page and updates design.

## Testing done - how did you test it/steps on how can another person can test it 
**_Searching with only filters_**
1. Visit `/search`.
2. Click on the `Filters` accordion and choose any number of filters you desire, and then click `Update results`. Make sure the `Filters` accordion now displays the same number of filters you added(e.g. Filters (3)).
3. Due to the `&or` logical operator, `Fuse.js` looks for the first match in the provided `keys` and then returns the result. In order to increase the accuracy(Fuse.js's `score`), I added some custom code. Basically, after a result returns from the original search, I then go back and see if the result had other matches based on the other filters chosen. For example, if the user selects the `COVID` and `Telehealth` categories, Fuse will only come back with the first match. However, if the result also has a `practice_category` that matches the second filter, I increase the score a little bit. This prevents the issue where results were coming back mostly with the same scores, because it was stopping on the first match(`short-circuit evaluation`).
4. To test this, go to the Google inspection tool and take a look at the `results` array. You can investigate the `item` within each `result` and see how the score has been improved if it has multiple matches for a single filtered search.
5. Reset the filters. Fill in the `Originating Facility` combo box with a `VISN` number and update the results.
6. It should fetch any practice that either has that `VISN` as an `initiating_facility`, or any practice that has a `practice_origin_facility` that belongs to the selected `VISN`.
7. If you have a practice with a matching `VISN` `initiating_facility`, it should be the first result, because I added some code to improve the score if the combo box value is a `VISN` and the result has an `initiating_facility` that matches that `VISN`.
8. Reset the filters and add a `VISN` to the `Adopting Facility` combo box, then update the results.
9. Similar to the `Originating Facility`, it fetch results that have a `diffusion_history` with a `facility_id` that belongs to the selected `VISN`. If the result has multiple matches, the score should be further improved.

**_Searching with filters and a search query_**
1. With the `$and` operator, results must match ALL of the conditions.
2. Reset the filters and add some text to the search input.
3. Add one filter and see if anything comes up.
4. Add another filter and see if the results are narrowed even more.
5. You can check the browser console to confirm each result matches every condition.

**_Searching with just a search query_**
1. This should function the same as the original search page.

**_Sorting options_**
1. Add a search term or filters of your choosing.
2. As long as there is more than one result for your search, there should be sorting options at the top right of the cards.
3. Make sure it's defaulted to `Sort by most relevant`.
4. Choose any of the other sort options and make sure they work as intended.
5. Note: `Recently added` is based on the practice's `created_at` column.

**_Loading more results_**
1. Reset filters, type `care` into the search bar and click `Search`.
2. There should be over 12 results.
3. If there is, the `Load more` button should appear below the fourth row of cards.
4. Click `Load more`.
5. If there are more than 24 results, make sure only the next 12 results are shown. If not, make sure the `Load more` button is hidden.
6. Choose a different sorting option and make sure the results are reset and the `Load more` button appears again.

**_Querying and search breadcrumb_**
1. Remove text from search bar and click `Search`.
2. Make sure the URL endpoint reverts back to `/search`.
3. Add any amount of filters and update results.
4. Click on any random practice card.
5. Once you get to the practice's show page, make sure the `Search` breadcrumb takes the user back to `/search`.
6. Click on the breadcrumb and then add some text to the search bar again and click `Search`.
7. Make sure the text is added to a query string within the endpoint(e.g. `/search?query=test`).
8. Click on a practice card.
9. This time, when you arrive at the practice's show page, make sure the `Search` breadcrumb contains the query string that was appended to the endpoint in the step above.

**_Mobile styling_**
1. Visit `/search` and use the Google inspection tool to adjust your viewport to `340px`(same as mockups).
2. Make sure the user flows and styling match the designs(or as close as possible hehe).
3. One important thing to note. If you click on the `Filters` button, an overlay appears with the filter accordions. This overlay still allows the user to scroll on the background page(similar to a modal). However, I added some code that saves the scroll position when the user first clicks the `Filters` button, and then when they either close the overlay or update the results, they should be returned to their original position on the page prior to opening the overlay. Make sure this works as intended.

**_Icon text_**
1. Visit `/search`.
2. Make sure you see the text `Enter a search term or use the filters to find matching practices`.
3. Add some text to the search bar and filters to the point where there are no results.
4. Make sure you see the text `There are currently no matches for your search on the Marketplace.`

**_Loading spinners_**
1. Organically, the data does not take very long to load, so seeing the spinners in action is very rare(I still haven't seen them without adding timeout functions lol).
2. If you want to see them in action, there are several spots in the code where you can wrap the code in this function:
```
setTimeout(function() {
   // The code goes here
}, 2000)
```
3. Around line `815` in `_search.js.erb`, or you can search for the text `Run the search`.
4. Around line `848` in `_search.js.erb`, or you can search for the text `Sort the results based on each sort option`. Add it to each case.
5. Around line `892` in `_search.js.erb`, or you can search for the code `if (window.location.pathname === '/search' && window.location.search !== '')`.
6. Around line `655` in `_search.js.erb`, or you can search for the text `Get the results and default to filtering based on score`.
7.  Around line `90` in `showMoreItems.js`, or you can search for the code `for (var i = _.nowNum; i < _.goNum; i++) {`. Include both the `For` loop and the `truncateText()` function.

**_Update_**
1. To account for only having 1 category, some code was adjusted.
2. To test, go to `practices/search_partials/_search_filters.html.erb`.
3. Replace line `39` with 
```
categories = Array(Category.where(is_other: false).where.not(name: 'Other').order(Arel.sql('LOWER(name) ASC')).uniq.first)
```
4. Visit `/search`.
5. Open the search filters accordion and make sure there are no errors and that you only see one category.

## Link to mock-ups/mock ups (image file if you have it) (if applicable)
https://www.figma.com/file/y9U9oLXTGe24O9W3X5UoYW/Home-%2B-Search-V2?node-id=1%3A171

## Acceptance criteria
- [Build Mobile First]

- [Filter accordion drops down]

- [Originating VISN or Facility combo box]

- [Dropdown listed alphabetically by VISN]

- [Adoption location combo box]

- [Category is below combo boxes and scrollable]

- [Update Results at Bottom]

- [Clear Filters button]

- [Have ability to scroll within filter]

- [Update Results and Reset Filter anchored to bottom]

- [Checkbox for category selection]

- [Relevant to you is the closest result to the search]

- [Load More OR Pagination (1, 2, 3, 4) whichever is easier]

## Definition of done
- [X] Unit tests written (if applicable)
- [X] e2e/accessibility tests written (if applicable)
- [X] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [X] A link has been provided to the originating JIRA issue
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by emyl3 — COMMENTED** [review]
This looks really good, Josh. Great work on this huge effort!! Just left a couple of nits.

**Review by emyl3 — DISMISSED** [review]
Looks good to me! Absolutely amazing work on this huge undertaking!! 😄

**Review by bradjohnson92008 — DISMISSED** [review]
Great job Josh - this was a big chunk of work.  :)

**Review by bradjohnson92008 — APPROVED** [review]
Looks good Josh - with only one category... app works fine.

**Review by emyl3 — APPROVED** [review]
Nice fixes, Josh! Works as intended for me!

**Pull request merged**
