### PR TITLE
DM-2309: Update admin site metrics

### PR DESCRIPTION
**Pull request by emyl3**
### JIRA issue link
[DM-2309](https://agile6.atlassian.net/browse/DM-2309)

## Description - what does this code do?
This PR addresses the following:
- Fixes counting "Site visit" and "User role" event tracking twice
- Begin tracking practice email counts (whenever a user clicks "Email practice" or "Contact [EMAIL HERE] with questions about this practice. " under the Contact section of `/practices/:slug`
- Begin tracking whenever a user navigates the the homepage of a page group (ex. visiting `/covid-19` counts as 1 visit; visiting `/covid-19/telehealth` does not count as a visit)
- Adds tooltips [based on this doc](https://docs.google.com/document/d/1nwSveCvQ9Rm_Uvc1NLd-iHydrE2K1NaNbSwRUhmgiD4/edit)
- Removes references to "commits" from the admin dashboard and metrics
- Updates the exportable metric spreadsheet with this data but excludes tooltip information

## Testing done - how did you test it/steps on how can another person can test it 
**"Site visit" and "User role" tracking fix**
Note: Have access to the `ahoy_events` table to see new entries to the DB
1. Be logged out
2. Navigate to a page (e.g. `/diffusion-map`)
3. Check the `ahoy_events` table to see "User role" is not logged for that visit
4. Check the `ahoy_events` table to see "Site visit" is logged ONCE for that visit
5. Login as a user
6. Navigate to any page
7. Check the `ahoy_events` table to see "User role" is logged ONCE for that visit
8. Check the `ahoy_events` table to see "Site visit" is logged ONCE for that visit
9. Repeat steps 1-8 as many different ways as desired
10. Log in as an admin
11. Go to `/admin` and click "Metrics"
12. Ensure you see this note "Note: An error in general traffic tracking was corrected in February 2021" under the "General Traffic" panel

**Tracking Practice email counts**
1. Log in as an admin
2. Go to `/admin` and click "Metrics"
3. Check that the Practice email counts are all 0
4. Go to a practice show page in a new tab
5. Click "Email practice" in the sidebar
6. Go back to the tab with the "Metrics" page open and hit refresh
7. Check that the values increased accordingly for both the stats overall and then for the practice
8. Go back to the tab with the practice show page open
9. Go to the "Contact" section and click the email of that practice
10. Go back to the tab with the "Metrics" page open and hit refresh
11. Check that the values increased accordingly for both the stats overall and then for the practice
12. Export the spreadsheet and ensure the information is correct
13. Repeat steps 4-12 with various practices, if desired
14. Ensure you see this note "Email counts tracking began in February 2021" under the "Email counts" header

**Tracking Home page of Page Group visits**
1. Log in as an admin
2. Go to `/admin` and click "Metrics"
3. Check that the "Custom Page Traffic" is all 0 
4. Ensure you see all the `page_group`s in the DB listed with a URL navigating to its homepage
5. Navigate to the homepage of a `page_group` (e.g. `/covid-19`)
6. Go to `/admin` and click "Metrics"
7. Check that the "Custom Page Traffic" values for that page increased accordingly
8. Navigate to a subpage of that `page_group` (e.g. `/covid-19/telehealth`)
9. Go to `/admin` and click "Metrics"
10. Check that the "Custom Page Traffic" values for that page has NOT increased accordingly
11. Create a new `page_group` and home page for that `page_group`
12. Go to `/admin` and click "Metrics"
13. Check that it has been added to the "Custom Page Traffic" panel
14. Ensure you see this note "Note: Custom page traffic tracking began in February 2021" under the "Custom Page Traffic" panel
15. Export the spreadsheet and ensure the information is correct

**Misc**
1. Log in as an admin
2. Make sure the tooltips appear according to the referenced Google Doc above
3. Ensure in there are no references to commits in the dashboard or the exportable spreadsheet

## Screenshots, Gifs, Videos from application (if applicable)
N/A

## Link to mock-ups/mock ups (image file if you have it) (if applicable)
N/A

## Acceptance criteria
- [X] Add definitions to metrics as tooltips
- [X] Figure out if Practice Page Views vs. Site Visits discrepancy is bounce rate or error or just confusing labeling (Work with  and  on this) (See attachment)
- [X] after correcting bullet point 2, put a note somewhere saying how site visit data was corrected on DATE HERE
- [X] Add COVID-19 Homepage to Metrics (Views, unique visits, visits)
- [X] Start capturing “Practice Emails,” number of times button in left hand nav and at bottom of page are click

## Definition of done
- [ ] Unit tests written (if applicable)
- [X] e2e/accessibility tests written (if applicable)
- [X] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [X] A link has been provided to the originating JIRA issue
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by JoshingYou1 — COMMENTED** [review]
Awesome job on this Elisa! The only thing I noticed when testing is that even if a Page Group does not have a page with the slug of `home`, we are still providing a link. When I click on the link, I get the `undefined method` error. Maybe we can write a condition that checks if any of the pages that belong to a certain page group have a slug of `home`, provide a link, and if not, just display text. I was thinking something like: 
```
custom_pages = PageGroup.all.select { |pg| pg.pages.where(slug: 'home').present? }.map{ |pg| pg.slug }
```

Other than that, everything worked as intended!! :smiley:

**Review by bradjohnson92008 — CHANGES_REQUESTED** [review]
Hey Elisa - I have two page groups defined - however, when I go to the dashboard -> Metrics page... I don't see them listed under the 'Custom Page Traffic' section.  
image ... 
image

**Comment by bradjohnson92008** [comment]
Hey Elisa  - disregard above comment... I did not have a "Home" page associated with any of those page groups.  Consider this though.. if there are no custom "home" pages (i.e., they are all removed ..etc) should we display the 'Custom Traffic" section at all on the metrics page?

**Comment by emyl3** [comment]
@bradjohnson92008 I pushed up a fix and added a test  to cover the scenario you described! Thank you :)

**Review by JoshingYou1 — APPROVED** [review]
Works great for me! Nice work again Elisa!

**Review by bradjohnson92008 — APPROVED** [review]
Works great - Thx Elisa!

**Pull request merged**
