### PR TITLE
Add file upload check and add implementation tests

### PR DESCRIPTION
**Pull request by emyl3**
### JIRA issue link
Addressed `Row 5` of the `Dev Review` tab of [this Google Sheet](https://docs.google.com/spreadsheets/d/163NX9FbvAA4Bzsb8ZfrDP5Eg8R41GAX1/edit#gid=208290614
)

## Description - what does this code do?
This PR does the following
- adds a client-side check and error messaging when a user tries to upload a file that is larger than 32 MB in PE Overview and Implementation sections
- adds more tests for the PE Implementation section
- organizes some test files

## Testing done - how did you test it/steps on how can another person can test it 
**File Upload**
- Log in as a user that can edit a practice
- Go to the PE Overview section of that practice
- Try uploading a file larger than 32MB
- you should see a warning and the file upload should clear
- Try uploading a file that works
- The upload should be successfully
- Add a new file to the PE Overview section and save
- Ensure it appears on the PV
- Repeat the above steps of the PE Implementation section
- BONUS: In the PE Overview/Implementation, the file's name should appear (not a file upload component) and the user should not be able to upload a new file when the file has been added to the save queue

## Screenshots, Gifs, Videos from application (if applicable)
Screen Shot 2020-10-19 at 1 32 04 PM
Screen Shot 2020-10-19 at 1 33 41 PM

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Unit tests written (if applicable)
- [X] e2e/accessibility tests written (if applicable)
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating JIRA issue
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by bradjohnson92008 — COMMENTED** [review]
Hey Elisa - great work.  I'm not clear on the bonus question...  are you saying that we can now only add one file to the queue at a time?  Or only add the same file to the queue once?  I thought it might be the latter.. but I was able to select a file.. add it to the queue, and then select the same exact file.. same filename, description ..etc and add to the queue and save both.

**Comment by emyl3** [comment]
> Hey Elisa - great work. I'm not clear on the bonus question... are you saying that we can now only add one file to the queue at a time? Or only add the same file to the queue once? I thought it might be the latter.. but I was able to select a file.. add it to the queue, and then select the same exact file.. same filename, description ..etc and add to the queue and save both.

Thank you, @bradjohnson92008 Sorry it was worded so confusingly 😅 You would still be able to add any number of files and it can be the same file (it doesn't matter). What I was trying to get at was...
when you add a file from here:
Screen Shot 2020-10-19 at 4 47 34 PM
And the page isn't saved yet like how it is below
Screen Shot 2020-10-19 at 4 47 54 PM
instead of the usa-file-input component... it's now just a `div` with the word `File:` and then the file name

I hope this is more clear 😅

**Review by bradjohnson92008 — APPROVED** [review]
Thanks for the clarification Elisa on the Bonus.  Works for me.  Rest of the PR LGTM as well.  Great job.

**Review by JoshingYou1 — APPROVED** [review]
Works as intended for me. Nice work Elisa!

**Pull request merged**
