### PR TITLE
Dm 2293

### PR DESCRIPTION
**Pull request by bradjohnson92008**
### JIRA issue link
https://agile6.atlassian.net/browse/DM-2293

## Description - what does this code do?
Allows users to click the search icon from the top nav-bar  even if the search text is blank in order to navigate to the search page.

## Testing done - how did you test it/steps on how can another person can test it 
1.  Login or don't... and click on the blue search icon in the top nav bar.
image
2.  Verify that the search page does not contain any queries or filters and the text in the search results displays "Enter a search term or use the filters to find matching practices".  
image

This text should display whenever there are no filters, originating or adopting locations, or queries supplied.  If search data is present (i.e., query, categories, originating location or adoption locations) and there are no results returned by the search the text in results area should say "There are currently no matches for your search on the Marketplace.".  i.e., 
image

3.  Add and Remove filters to test that all is working well with search.

## Link to mock-ups/mock ups (image file if you have it) (if applicable)
Figma: https://www.figma.com/file/y9U9oLXTGe24O9W3X5UoYW/Home-%2B-Search-V2?node-id=1%3A171

## Acceptance criteria
When box is blank, clicking on the search icon (magnifying glass) takes you to the search page

## Definition of done
- [ ] Unit tests written (if applicable)
- [ ] e2e/accessibility tests written (if applicable)
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating JIRA issue
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by JoshingYou1 — COMMENTED** [review]
Great work Brad!! Just a couple of comments for ya.

1. Can we remove the query string from the end of the URL when the user clicks on the icon with not text?
Screen Shot 2021-01-21 at 10 36 58 AM

2. Can we write a unit test to cover this use case?

**Review by emyl3 — COMMENTED** [review]
nothing else to add to what josh said! nice work brad! 👍

**Comment by bradjohnson92008** [comment]
Removed query param from url.. if search field value blank.  Added unit test for this case.

**Review by JoshingYou1 — APPROVED** [review]
Everything works as intended. Thank you Brad!!!

**Pull request merged**
