### PR TITLE
DM-2149: Update practice cards with new designs

### PR DESCRIPTION
**Pull request by emyl3**
### JIRA issue link
[DM-2149](https://agile6.atlassian.net/browse/DM-2149)

## Description - what does this code do?
This PR updates the practice cards with the new designs.

## Testing done - how did you test it/steps on how can another person can test it 
1. Log in as a user that can view a practice.
2. Go to the home page. Ensure the practice cards are designed according to Figma.
3. Ensure you can bookmark and un-bookmark a practice.
4. Go to your profile page. Ensure the practice cards you favorited and the practices you created are designed according to Figma.
5. Go to a custom page that is created in `/admin/pages` with a practices component displays the practice cards designed according to Figma.
6. Go to a practice's `/planning-checklist` ensure the practice card appears as designed in Figma.
7. Go to a practice partner's page and ensure the practice card appears as designed in Figma.
8. Ensure you can't see a bookmark button when you are not signed in.
9. Ensure their are ellipses for titles after 2 lines, for practice summary after 4 lines, for practice origin after 2 lines
10. Ensure  practices without a thumbnail have a black-gray-ish background and the title on top of that.

## Link to mock-ups/mock ups (image file if you have it) (if applicable)
[Figma](https://www.figma.com/file/y9U9oLXTGe24O9W3X5UoYW/Home-%2B-Search-V2?node-id=263%3A2241)

## Acceptance criteria
- [X] Build mobile first
- [X] Use new layout
- [X] Use new size
- [X] Build new card without picture and with thumbnail
- [X] Look at places this touches and adjust accordingly
- [X] Up to 26 characters in title, 13 on each line, 125 characters over four lines for “Body” (Estimate)
- [X] Set height for characters
- [X] Date and location cuts off after two lines
- [X] For title, make sure there’s ellipses if it gets cut off 

## Definition of done
- [ ] Unit tests written (if applicable)
- [ ] e2e/accessibility tests written (if applicable)
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating JIRA issue
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by JoshingYou1 — COMMENTED** [review]
Great work Elisa!! I noticed just a couple of small things. 

1. On the users show page, there only a small margin between `favorited` and `created` practices. 
Screen Shot 2020-11-08 at 4 53 16 PM

2. When I visited a page group page, I noticed the image portion of the card was a bit wider than the text portion, and the bookmark circle was a tad off.
Screen Shot 2020-11-08 at 5 04 21 PM

3. I added enough text to the tagline to take up more than four lines on the card, but the ellipses never showed up.
Screen Shot 2020-11-08 at 5 03 28 PM

**Comment by emyl3** [comment]
@JoshingYou1 Ok I addressed the issues (except for the tagline ellipses issue because I could not repro)! thank you!!

Fix margin between "Bookmarked" and "Created" practices
Screen Shot 2020-11-09 at 9 29 40 AM

Fix practice cards on page view
Screen Shot 2020-11-09 at 9 57 35 AM

Tagline ellipses (from my local machine)
Screen Shot 2020-11-09 at 10 13 17 AM

**Review by bradjohnson92008 — COMMENTED** [review]
Great job Elisa.  I was able to get through all the scenarios.  Only think I noticed is what Josh caught regarding the tagline ellipses not displaying if text is greater than 4 lines.

image

**Comment by bradjohnson92008** [comment]
Thats weird.. I left and came back to the home page and now I see the elipses..  :) 

image

**Review by JoshingYou1 — DISMISSED** [review]
Great work Elisa!!

**Review by JoshingYou1 — APPROVED** [review]
Thank you for making that last change to the taglines. Great work!!

**Pull request merged**
